name: Testeando chamfer con harta regularizacion y cabezas
input_resolution: 32
amount_of_heads: 20
out_features: 4
use_bn: true
loss_used: chamfer
reg_coef: 1.0
max_sde: 0.001
angle_threshold: 10.0
sde_fn: chamfer
phc_angle: 1.0
phc_dist_percent: 0.01
train_data_path: /data/gsanteli/voxel_dataset_32_full
test_data_path: /data/gsanteli/voxel_dataset_test_32_full_v2
predict_data_path: /data/gsanteli/voxel_dataset_test_32_full_v2
train_val_split: 0.9
sample_size: 2048
batch_size: 32
shuffle: true
n_workers: 8
